export type ComponentCategory = 'Forms' | 'Feedback' | 'Data' | 'Media' | 'Layout' | 'Navigation' | 'Overlays' | 'Desktop';

export type ComponentProp = {
  name: string;
  type: string;
  defaultValue: string;
  description: string;
};

export type ComponentDoc = {
  name: string;
  slug: string;
  category: ComponentCategory;
  description: string;
  states: string[];
  accessibility: string;
  props: ComponentProp[];
};

const children = { name: 'children', type: 'ReactNode', defaultValue: '—', description: 'Content rendered by the component.' };
const className = { name: 'className', type: 'string', defaultValue: '—', description: 'Adds product-owned styles without replacing Ink contracts.' };
const disabled = { name: 'disabled', type: 'boolean', defaultValue: 'false', description: 'Prevents interaction and exposes the unavailable state.' };
const density = { name: 'density', type: 'compact | default | touch', defaultValue: 'provider', description: 'Overrides the inherited interaction density.' };

const define = (category: ComponentCategory, items: Array<Omit<ComponentDoc, 'category'>>): ComponentDoc[] => items.map((item) => ({ category, ...item }));

export const componentRegistry: ComponentDoc[] = [
  ...define('Forms', [
    { name: 'Button', slug: 'button', description: 'Triggers an immediate action with consistent hierarchy and density.', states: ['default', 'hover', 'focus', 'pressed', 'loading', 'disabled'], accessibility: 'Use a verb label. Loading preserves the accessible name and disables repeated activation.', props: [{ name: 'variant', type: 'primary | secondary | quiet', defaultValue: 'secondary', description: 'Sets visual action hierarchy.' }, density, { name: 'loading', type: 'boolean', defaultValue: 'false', description: 'Shows progress and blocks repeated activation.' }] },
    { name: 'ButtonGroup', slug: 'button-group', description: 'Groups related actions into one labelled control set.', states: ['default', 'focus-within', 'disabled child'], accessibility: 'Provide label when the surrounding heading does not name the group.', props: [{ name: 'label', type: 'string', defaultValue: '—', description: 'Accessible group name.' }, density, children] },
    { name: 'IconButton', slug: 'icon-button', description: 'Compact action whose visible content is an icon or glyph.', states: ['default', 'hover', 'focus', 'pressed', 'disabled'], accessibility: 'A concise label is required because the glyph is not a sufficient accessible name.', props: [{ name: 'label', type: 'string', defaultValue: 'required', description: 'Accessible action name.' }, density, disabled] },
    { name: 'TextField', slug: 'text-field', description: 'Single-line labelled text input with description and validation.', states: ['empty', 'filled', 'focus', 'readonly', 'invalid', 'disabled'], accessibility: 'Label, description, and error are connected to the native input through stable IDs.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Visible and accessible field name.' }, { name: 'description', type: 'ReactNode', defaultValue: '—', description: 'Persistent guidance shown before validation.' }, { name: 'error', type: 'ReactNode', defaultValue: '—', description: 'Marks the input invalid and connects the error message.' }] },
    { name: 'TextArea', slug: 'text-area', description: 'Multi-line text input using the same field contract as TextField.', states: ['empty', 'filled', 'focus', 'readonly', 'invalid', 'disabled'], accessibility: 'Keep the label visible and describe expected length or format before an error occurs.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Visible and accessible field name.' }, { name: 'resize', type: 'CSS behavior', defaultValue: 'vertical', description: 'Allows content growth without breaking horizontal layouts.' }, { name: 'error', type: 'ReactNode', defaultValue: '—', description: 'Connected validation feedback.' }] },
    { name: 'Checkbox', slug: 'checkbox', description: 'Independent binary choice with optional supporting copy.', states: ['unchecked', 'checked', 'focus', 'invalid', 'disabled'], accessibility: 'Use for independent choices; use RadioGroup when exactly one option must be selected.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Choice name and hit target.' }, { name: 'description', type: 'ReactNode', defaultValue: '—', description: 'Supporting context.' }, { name: 'error', type: 'ReactNode', defaultValue: '—', description: 'Connected validation feedback.' }] },
    { name: 'RadioGroup', slug: 'radio-group', description: 'Selects exactly one value from a visible set.', states: ['unchecked', 'checked', 'focus', 'disabled'], accessibility: 'The group label names the question; each option label names one mutually exclusive answer.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Accessible group name.' }, { name: 'options', type: 'RadioOption[]', defaultValue: '[]', description: 'Visible choices and values.' }, { name: 'value', type: 'string', defaultValue: '—', description: 'Controlled selected value.' }] },
    { name: 'Switch', slug: 'switch', description: 'Toggles a setting that takes effect immediately.', states: ['off', 'on', 'focus', 'disabled'], accessibility: 'Use for immediate settings, not for selections submitted later with a form.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Names the setting.' }, { name: 'checked', type: 'boolean', defaultValue: '—', description: 'Controlled on/off state.' }, disabled] },
    { name: 'Select', slug: 'select', description: 'Custom single-value listbox with consistent Ink presentation.', states: ['closed', 'open', 'focus', 'selected', 'invalid', 'disabled'], accessibility: 'Implements combobox/listbox keyboard behavior; options retain visible text labels.', props: [{ name: 'options', type: 'SelectOption[]', defaultValue: '[]', description: 'Available labels and values.' }, { name: 'placeholder', type: 'string', defaultValue: '—', description: 'Prompt shown before selection.' }, { name: 'error', type: 'ReactNode', defaultValue: '—', description: 'Connected validation feedback.' }] },
    { name: 'Combobox', slug: 'combobox', description: 'Searchable single-value list for longer option sets.', states: ['empty', 'querying', 'open', 'selected', 'no results', 'disabled'], accessibility: 'Announces the active option and supports arrow, Enter, and Escape keyboard behavior.', props: [{ name: 'options', type: 'ComboboxOption[]', defaultValue: '[]', description: 'Searchable labels and values.' }, { name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Visible and accessible field name.' }, disabled] },
  ]),
  ...define('Feedback', [
    { name: 'Alert', slug: 'alert', description: 'Inline feedback scoped to nearby content or an action.', states: ['info', 'success', 'warning', 'danger'], accessibility: 'Choose live behavior based on urgency; do not announce static content on initial page load.', props: [{ name: 'tone', type: 'neutral | ok | warning | danger', defaultValue: 'neutral', description: 'Semantic urgency and screentone.' }, { name: 'title', type: 'ReactNode', defaultValue: '—', description: 'Short outcome summary.' }, children] },
    { name: 'Banner', slug: 'banner', description: 'Page- or workspace-level notice with optional recovery actions.', states: ['info', 'success', 'warning', 'danger'], accessibility: 'Place near the affected scope and keep recovery actions inside the same landmark.', props: [{ name: 'tone', type: 'FeedbackTone', defaultValue: 'neutral', description: 'Semantic urgency.' }, { name: 'title', type: 'ReactNode', defaultValue: 'required', description: 'Notice summary.' }, { name: 'actions', type: 'ReactNode', defaultValue: '—', description: 'Contextual recovery actions.' }] },
    { name: 'ErrorState', slug: 'error-state', description: 'Replaces a region that cannot render and provides recovery.', states: ['section failure', 'page failure', 'with details'], accessibility: 'Keep the failed region in place so context is preserved; expose retry before secondary actions.', props: [{ name: 'title', type: 'ReactNode', defaultValue: 'required', description: 'Failure summary.' }, { name: 'description', type: 'ReactNode', defaultValue: '—', description: 'User-facing consequence.' }, { name: 'actions', type: 'ReactNode', defaultValue: '—', description: 'Recovery controls.' }] },
    { name: 'Toast', slug: 'toast', description: 'Transient confirmation or background-process feedback.', states: ['success', 'warning', 'danger', 'dismissed'], accessibility: 'Never use as the only location for form errors or information required to continue.', props: [{ name: 'open', type: 'boolean', defaultValue: '—', description: 'Controlled visibility.' }, { name: 'tone', type: 'FeedbackTone', defaultValue: 'neutral', description: 'Semantic outcome.' }, { name: 'onOpenChange', type: '(open) => void', defaultValue: '—', description: 'Synchronizes visibility.' }] },
    { name: 'StatusMark', slug: 'status-mark', description: 'Compact semantic status that combines screentone and visible text.', states: ['neutral', 'healthy', 'pending', 'danger'], accessibility: 'Meaning is always present in text and never depends on color or pattern alone.', props: [{ name: 'tone', type: 'neutral | ok | warning | danger', defaultValue: 'neutral', description: 'Semantic status.' }, { name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Visible status meaning.' }] },
    { name: 'Progress', slug: 'progress', description: 'Determinate progress with a visible task label.', states: ['empty', 'partial', 'complete'], accessibility: 'Provide the current numeric value and a label that identifies the task.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Names the operation.' }, { name: 'value', type: 'number', defaultValue: '0', description: 'Progress from 0 to 100.' }] },
  ]),
  ...define('Data', [
    { name: 'DataTable', slug: 'data-table', description: 'Controlled data grid composition for product-owned datasets.', states: ['loading', 'populated', 'selected', 'empty', 'stale error', 'blocking error'], accessibility: 'Caption names the dataset; sortable headers, selection, and pagination expose native semantics.', props: [{ name: 'columns', type: 'DataTableColumn[]', defaultValue: 'required', description: 'Column headers and renderers.' }, { name: 'rows', type: 'T[]', defaultValue: 'required', description: 'Visible product-owned rows.' }, { name: 'pagination', type: 'DataTablePagination', defaultValue: '—', description: 'Controlled page state.' }] },
    { name: 'Table', slug: 'table', description: 'Semantic table primitives for static or lightly interactive datasets.', states: ['header', 'body', 'caption', 'overflow'], accessibility: 'Use a caption and scoped column headers; do not use a table only for visual alignment.', props: [{ name: 'variant', type: 'semantic HTML', defaultValue: 'table', description: 'Composes native table elements.' }, children, className] },
    { name: 'FilterChip', slug: 'filter-chip', description: 'Visible active-filter token with a removal action.', states: ['active', 'focus', 'removing'], accessibility: 'The remove button names both the action and filter value.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Visible active filter.' }, { name: 'onRemove', type: '() => void', defaultValue: 'required', description: 'Clears this filter.' }] },
    { name: 'Pagination', slug: 'pagination', description: 'Consistent link- or button-based movement through known pages.', states: ['first', 'middle', 'last', 'current', 'disabled'], accessibility: 'Current page uses aria-current; previous and next controls have explicit names.', props: [{ name: 'page', type: 'number', defaultValue: '—', description: 'Controlled current page for button mode.' }, { name: 'pageCount', type: 'number', defaultValue: '—', description: 'Total page count.' }, children] },
  ]),
  ...define('Media', [
    { name: 'FileUpload', slug: 'file-upload', description: 'Native file selection wrapped in an accessible drop surface.', states: ['idle', 'drag active', 'selected', 'invalid', 'disabled'], accessibility: 'The native file input remains operable; accepted formats and limits are visible before selection.', props: [{ name: 'label', type: 'ReactNode', defaultValue: 'required', description: 'Names the upload purpose.' }, { name: 'accept', type: 'string', defaultValue: '—', description: 'Native accepted file hint.' }, { name: 'onFilesChange', type: '(files) => void', defaultValue: 'required', description: 'Returns selected files to the product.' }] },
    { name: 'FileList', slug: 'file-list', description: 'Product-controlled upload queue with progress and recovery.', states: ['queued', 'uploading', 'success', 'error'], accessibility: 'Progress and errors remain attached to each file; retry and removal buttons name the file.', props: [{ name: 'items', type: 'UploadFileItem[]', defaultValue: '[]', description: 'Queue and status data.' }, { name: 'onRetry', type: '(item) => void', defaultValue: '—', description: 'Retries one failed item.' }, { name: 'onRemove', type: '(item) => void', defaultValue: '—', description: 'Removes one item.' }] },
    { name: 'ImageSurface', slug: 'image-surface', description: 'Aspect-ratio image frame with caption and deterministic fallback.', states: ['loading', 'loaded', 'fallback'], accessibility: 'Meaningful images require alt text; decorative images use an empty alt.', props: [{ name: 'src', type: 'string', defaultValue: 'required', description: 'Image source.' }, { name: 'alt', type: 'string', defaultValue: 'required', description: 'Accessible alternative.' }, { name: 'aspectRatio', type: 'square | video | portrait | auto', defaultValue: 'auto', description: 'Stable layout ratio.' }] },
    { name: 'ImageGallery', slug: 'image-gallery', description: 'Thumbnail collection with keyboard-accessible lightbox.', states: ['grid', 'lightbox', 'previous', 'next'], accessibility: 'Every trigger names the image; the modal traps focus and supports Escape and arrow navigation.', props: [{ name: 'items', type: 'ImageGalleryItem[]', defaultValue: '[]', description: 'Images, alternatives, and captions.' }] },
    { name: 'Avatar', slug: 'avatar', description: 'Identity image with deterministic initials fallback.', states: ['image', 'initials', 'small', 'large'], accessibility: 'The visible name supplies fallback initials; avoid repeating adjacent identity text unnecessarily.', props: [{ name: 'name', type: 'string', defaultValue: 'required', description: 'Identity and fallback source.' }, { name: 'src', type: 'string', defaultValue: '—', description: 'Optional portrait source.' }, { name: 'size', type: 'sm | md | lg', defaultValue: 'md', description: 'Display size.' }] },
  ]),
  ...define('Layout', [
    { name: 'Surface', slug: 'surface', description: 'Semantic background and border container.', states: ['default', 'elevated', 'recessed'], accessibility: 'Surface adds no implicit landmark; choose the correct semantic element around it.', props: [{ name: 'variant', type: 'default | elevated | recessed', defaultValue: 'default', description: 'Visual depth.' }, children, className] },
    { name: 'Card', slug: 'card', description: 'Structured content surface with header, body, and footer slots.', states: ['default', 'with action', 'status'], accessibility: 'Card does not invent semantics; headings inside cards should follow the page hierarchy.', props: [children, className] },
    { name: 'Stack', slug: 'stack', description: 'Vertical layout primitive driven by shared spacing tokens.', states: ['compact gap', 'default gap', 'large gap'], accessibility: 'Layout-only component with no semantic role.', props: [{ name: 'gap', type: 'xs | sm | md | lg | xl', defaultValue: 'md', description: 'Vertical token gap.' }, { name: 'align', type: 'LayoutAlign', defaultValue: 'stretch', description: 'Cross-axis alignment.' }, children] },
    { name: 'Inline', slug: 'inline', description: 'Horizontal wrapping layout driven by shared spacing tokens.', states: ['nowrap', 'wrap', 'distributed'], accessibility: 'Layout-only component with no semantic role.', props: [{ name: 'gap', type: 'LayoutGap', defaultValue: 'md', description: 'Horizontal token gap.' }, { name: 'wrap', type: 'boolean', defaultValue: 'false', description: 'Allows items to wrap.' }, children] },
  ]),
  ...define('Navigation', [
    { name: 'Tabs', slug: 'tabs', description: 'Switches between related panels within one context.', states: ['inactive', 'active', 'focus'], accessibility: 'Arrow keys move through tabs; each tab is associated with exactly one panel.', props: [{ name: 'value', type: 'string', defaultValue: '—', description: 'Controlled active tab.' }, { name: 'defaultValue', type: 'string', defaultValue: '—', description: 'Initial uncontrolled tab.' }, children] },
    { name: 'Accordion', slug: 'accordion', description: 'Progressively discloses sections of supporting content.', states: ['collapsed', 'expanded', 'focus'], accessibility: 'Triggers remain headings/buttons and expose expanded state to assistive technology.', props: [{ name: 'type', type: 'single | multiple', defaultValue: 'single', description: 'Expansion model.' }, { name: 'collapsible', type: 'boolean', defaultValue: 'false', description: 'Allows all items to close.' }, children] },
    { name: 'Breadcrumb', slug: 'breadcrumb', description: 'Shows location within a stable product hierarchy.', states: ['ancestor', 'current'], accessibility: 'Rendered as labelled navigation; the terminal item uses aria-current.', props: [{ name: 'label', type: 'string', defaultValue: 'Breadcrumb', description: 'Navigation landmark name.' }, children] },
  ]),
  ...define('Overlays', [
    { name: 'Dialog', slug: 'dialog', description: 'Modal decision or focused task that temporarily blocks the page.', states: ['closed', 'open', 'validation error'], accessibility: 'Focus moves into the dialog, remains trapped, and returns to the trigger on close.', props: [{ name: 'title', type: 'ReactNode', defaultValue: 'required', description: 'Accessible dialog name.' }, { name: 'description', type: 'ReactNode', defaultValue: '—', description: 'Explains the task or consequence.' }, children] },
    { name: 'Drawer', slug: 'drawer', description: 'Edge-mounted inspector that preserves workspace context.', states: ['closed', 'left', 'right'], accessibility: 'Uses modal focus management; title and close action remain available at narrow viewports.', props: [{ name: 'side', type: 'left | right', defaultValue: 'right', description: 'Entrance edge.' }, { name: 'title', type: 'ReactNode', defaultValue: 'required', description: 'Accessible drawer name.' }, children] },
    { name: 'Menu', slug: 'menu', description: 'Short list of actions associated with one trigger.', states: ['closed', 'open', 'active item', 'disabled item'], accessibility: 'Arrow keys navigate items; Escape closes and focus returns to the trigger.', props: [{ name: 'modal', type: 'boolean', defaultValue: 'true', description: 'Controls outside interaction while open.' }, children] },
    { name: 'Popover', slug: 'popover', description: 'Non-modal contextual content anchored to a trigger.', states: ['closed', 'open'], accessibility: 'Use for supporting controls or information; use Dialog for blocking decisions.', props: [{ name: 'open', type: 'boolean', defaultValue: '—', description: 'Controlled visibility.' }, children] },
    { name: 'Tooltip', slug: 'tooltip', description: 'Brief supplemental label for pointer and keyboard users.', states: ['closed', 'delayed open'], accessibility: 'Never place essential instructions or interactive content inside a tooltip.', props: [{ name: 'delayDuration', type: 'number', defaultValue: 'provider', description: 'Delay before display.' }, children] },
  ]),
  ...define('Desktop', [
    { name: 'Toolbar', slug: 'toolbar', description: 'Horizontal set of high-frequency workspace actions.', states: ['default', 'focus within', 'overflow'], accessibility: 'Provide a label; group related actions and preserve logical keyboard order.', props: [{ name: 'aria-label', type: 'string', defaultValue: 'required', description: 'Names the action region.' }, children, className] },
    { name: 'Sidebar', slug: 'sidebar', description: 'Persistent desktop navigation or contextual inspector surface.', states: ['navigation', 'inspector', 'narrow'], accessibility: 'Give navigation sidebars a unique label; do not rely on position alone.', props: [{ name: 'aria-label', type: 'string', defaultValue: '—', description: 'Names the landmark when used for navigation.' }, children, className] },
  ]),
];

export function findComponent(slug: string) {
  return componentRegistry.find((component) => component.slug === slug);
}
